name: tikplayer

services:
  tikplayer:
    build:
      context: .
    image: tikplayer:2.4
    container_name: tikplayer
    restart: unless-stopped
    ports:
      - "1015:8000"
    env_file:
      - .env
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - "44"
      - "109"
    environment:
      - LIBVA_DRIVER_NAME=iHD
      - TRANSCODE_BACKENDS=qsv,vaapi,cpu
    volumes:
      - ./image:/app/image
      - ./data:/app/data
      - ./index.html:/app/index.html:ro
      - ./offline.html:/app/offline.html:ro
      - ./main.py:/app/main.py:ro
      - ./sw.js:/app/sw.js:ro
      - ./manifest.json:/app/manifest.json:ro
      - ./static:/app/static:ro
    shm_size: "2gb"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
